################################################
#                  Hitech95                    #
#                                              #
#                Developed by                  #
#                 Hitech95                     #
#                                              #
#                                              #
#              http://kytech.it                #
################################################

#Do NOT touch this!
config-version: 0

#Enable debug messages
debug: false

#Enables the udpdate checker. This will enabled
#anyone with the perm bw.system.updatenotify to
#be notified when a new update is avalible
check-for-updates: true

#Set how many players are needed for the game
#to auto-start. Once the player limit is reached
#it will wait for x amount of seconds for
#additional players. Auto start vote means that
#x percent of players need to vote with /bw vote
#for the game to begin
auto-start-players: 2
auto-start-time: 20

#Set if weather is allowed
weather-allowed: false

#If the player queue is enabled then if a player
#tries to join a game that is not joinable
#(ie ingame) the player will be added to a
#queue line to join the next time the game
#is open
enable-player-queue: true

#If set to true, commands not associated with
#the Bow Warfare will not be allowed to be run 
#by players in-game.
disallow-commands: true

#If disallow-commands is set to true, you can use
#the cmdwhitelist section below to whitelist certain
#commands.
cmdwhitelist: 
- 'kit'

#Block Filtering
block:
  place:
    whitelist:
    - 46
  break:
    whitelist:
    - 46

#Set default limits for a GameType -- WIP
limits: 
    FFA:
        kill: 25
        maxp: 16
    TDM:
        kill: 60
        maxp: 20
    CTF:
        time: 500
        maxp: 8
    LMS:        
        life: 4
        minp: 8
        time: 300        
    INF:
        time: 800
        maxp: 10
        minp: 2

#How many blocks to rollback per-tick
#The higher this settings the fast each
#arena will be reset but will cause more
#lag
rollback:
  per-tick: 100
  
  
#Settings for connecting to and 
#SQL server. These settings will
#be used for  the online webstats
#Prefix is what all tables used for 
#Bow Warfare will be
#prefixed with. This should stay the same
#for most cases.
sql:
  host: 'localhost'
  port: 3306
  user: 'root'
  pass: ''
  database: 'bowwarfare'
  prefix: 'bw_'


###########################################################
######################  Economy ###########################
###########################################################

#Can be written both negative and positive values​​.
#the money you win is a win singiolo player in case of winning.
#Similarly loose is the price that each player will have to pay.
#kill is the price that will be given to the player who makes a kill.
#death is similar to kill, it's the price to pay when you are killed.
economy:
  enabled: false
  win: 5
  loose: -1
  kill: 1
  death: 0
  
  
###########################################################
#######################  Stats ############################
###########################################################
  
#Settings for the webstats. If enabled, stats 
#such as k/d record, wins, win streaks, kill
#streaks, etc. will be saved. 

stats:
  enabled: false
  webserver:
    enabled: false
    port: 8080
  points:
    kill: 10
    win: 100
    position: 7
    killstreak:
      base: 10
      multiplier: 2
  killstreak:
    level1: '&e{player}&7 got a Double Kill!'
    level2: '&e{player}&9 got a Multi Kill!'
    level3: '&e{player}&5 got an Ultra Kill!'
    level4: '&e{player}&4 got an Unbelievable Kill!'
    level5: '&e{player}&a&kii&4&l Unbelievable+!&a&kii'
    
    
    


