name: BowWarfare-Reloaded
version: ${project.version}.${BUILD_NUMBER}
main: it.kytech.bowwarfare.BowWarfare
authors: [Hitech95, YoshiGenius]
description: Fully Automated BowWarfare Plugin!
softdepend: [WorldEdit, Vault, DisguiseCraft]

commands:
    bowwarfare:
        description: Bow Warfare Command
        usage: /bw <command> <args>
        aliases: [bowwarfare, bw]

